### DISCUSSION TITLE
Add support for themes

### DISCUSSION THREAD

**Discussion by tlvenn** [fluxonui/fluxon#17] [Feature Requests]
It would be great to have a solution to theme Fluxon components.
Maybe taking inspiration from the approach used by [shadcn](https://ui.shadcn.com/themes) or something similar.

**Comment by tlvenn** [comment]
DaisyUI uses a similar [approach](https://daisyui.com/docs/themes/) as well.

**Comment by tlvenn** [comment]
I am surprised it seems I am the only one struggling with this... The other UI libs in the space, to my knowledge, generate the code for the components you want to use using mix and therefore you can customize it, at the price of dealing with merge conflicts down the road but a few tailwindcss classes here and there are pretty painless to merge.

I think this approach was first done with https://mishka.tools/chelekom and [saladUi](https://github.com/bluzky/salad_ui) is now offering this option too (you can still use it as a library if you want)
![CleanShot 2025-01-14 at 14 36 56@2x](https://github.com/user-attachments/assets/31798de0-128c-4010-abc6-87ac5e7cae19)

Fluxon is currently not approaching this from this angle and instead we rely on a dependency at runtime and the only way to customize a given component across a whole project is to wrap it but there are so many things that you can't do properly / propagate this way, so it feels very much limited and cumbersome.

Is there any chance that Fluxon could offer a similar approach as well ? This is probably a much more versatile / powerful solution and probably even easier to implement given the open source prior arts and that it does not have any impact on the components themselves.

@andrielfn any thought on the subject ?

**Reply by andrielfn** [reply]
Hey @tlvenn, sorry for taking so long to respond!

Thanks for bringing this up! This has been one of the most common topics people ask about since I released Fluxon UI - not just here, but also through emails and X messages.

I'm 100% with you on this - having components in the user's codebase would be much better than having them as a dependency. There are so many benefits to this approach that I could talk about for hours!

When I started Fluxon, my main goal was to create components that look good, work well, and are accessible right out of the box - something that would work smoothly for most apps. I initially packed everything into a hex package since it was the easiest way to use in some of my own apps and consequently distribute it. But on the other hand, I completely understand there's a lot to improve in the Fluxon ecosystem - better docs, simpler ways to customize components, more flexible installation options, and so on.

In the short to medium term, I'm focusing on two main things: making sure the current components are rock-solid (fixing bugs and adding improvements) and shipping new components that people keep asking for (like date pickers, autocomplete, pagination, toast notifications, etc). Once I'm happy with how the components are working, I then plan to start working on a "Fluxon 2.0". The biggest change will be making the library a "non-runtime dependency", exactly like you suggested.

I know this might not cover everything you asked about, but I hope it helps explain some of my future plans for Fluxon UI.

Meanwhile, I'd love to hear more about the specific issues you're having with customization and theming - maybe I can help you out with those now!

**Comment by tlvenn** [comment]
Thank you for your response, @andrielfn.

I completely understand your perspective, but I believe Fluxon already offers a robust set of features, and expanding its surface area further might not be the best approach at this stage. By addressing this specific issue first, I’m confident you’ll attract a larger customer base, which will ultimately benefit the Fluxon ecosystem and pave the way for developing additional components in the future.

I encourage you exploring [Igniter](https://hexdocs.pm/igniter/readme.html), a tool specifically designed to handle this type of problem. Interestingly, Chelekon utilizes Igniter to power its mix tasks and patch user project files.

Take a look at the code, it’s concise and straightforward. I’m certain you could create something similar without much effort.
> https://github.com/mishka-group/mishka_chelekom/tree/master/lib/mix/tasks

**Comment by blset** [comment]
I agree this would be the most important benefit giving what's already there,  a sort of super core component replacement

but nothing prevents you already duplicating for instance the button component into a my_button component and customize.
of course this breaks the link with future updates, but it's already the case with core components

the core of fluxon is in the js but the components can be easely redefined if needed without the need for a generator that puts files in your components tree, which is maybe a lot of work to set up


Currently for Button for instance, If you need to customize only the color and don't want to duplicate button.ex
you  cannot use a customized color like newcolor that would be defined in the tailwind theme
 although it would seem relatively straightforward to just substitute the color name and keep the rest in this excerpt from button.ex
```
yellow" => %{
      "default" => [
        "text-yellow-600 dark:text-yellow-400 border-yellow-300 dark:border-yellow-500/50",
        "before:from-yellow-400/20 dark:before:from-yellow-500/20",
        "hover:after:bg-yellow-100/30 dark:hover:after:bg-yellow-500/10"
      ],

```


I suppose this won't work because tailwind needs to see the final class name explicitly to keep the class
so currently duplicating in your lib tree seems the most  simple, with manual update like for core components on future fluxon updates

**Comment by mikesax** [comment]
> When I started Fluxon, my main goal was to create components that look good, work well, and are accessible right out of the box - something that would work smoothly for most apps.

Although themes are tempting, I am concerned that the added complexity is too high of a price to pay. I love Fluxon because you have great taste and you’ve delivered exactly what you set out to: “look good, work well, and are accessible”. I believe your simple mission is golden.

**Reply by tlvenn** [reply]
> > When I started Fluxon, my main goal was to create components that look good, work well, and are accessible right out of the box - something that would work smoothly for most apps.
> 
> Although themes are tempting, I am concerned that the added complexity is too high of a price to pay. I love Fluxon because you have great taste and you’ve delivered exactly what you set out to: “look good, work well, and are accessible”. I believe your simple mission is golden.

The theming aspect could / should be entirely opt-in, just like `chelekom` & `saladUi`. It you don't want to theme / customize the components directly, simply use the dependencies.

**Comment by absowoot** [comment]
While I agree that the built-in styles in Fluxon are nice, I feel that adding support for themes would be beneficial now that Phoenix has added support for Tailwind 4. 

As I rebuild my app with Fluxon, I'm often having to write extensive classes to have the elements match my theme and undo the default styling (looking at you default button with your :after pseudoclass that sets a background color on hover). For some components (like the autocomplete), we can only change input styling by writing CSS in app.css because there is no `class` attribute. 

The components are built and function very well, but not allowing components to be themed out of the box is very prohibitive and limits the usability of this library to in-house projects only.

**Comment by andrielfn** [comment]
Hey everyone! Been a while since I talked about theme support in Fluxon. Still working on it, I promise! Sorry for the delay - been juggling other projects, some travel, and life stuff.

Wanted to share how I'm building this and get your thoughts early on.

So basically, I'm following the same pattern as daisyUI, shad/cn, and others - you'll customize colors through CSS variables.

You'll need to add something like `@import "fluxon/theme"` in your `app.css`. This handles the default theme colors (light and dark). Here's what it looks like:

```css
:root {
  color-scheme: light dark;

  /* === Primary & Content === */
  --primary: light-dark(var(--color-zinc-800), var(--color-white));
  --primary-hover: color-mix(in srgb, var(--primary), black 4%);

  --content: light-dark(var(--color-zinc-700), var(--color-zinc-200));
  --content-subtle: light-dark(var(--color-zinc-600), var(--color-zinc-300));
  --content-muted: light-dark(var(--color-zinc-500), var(--color-zinc-400));
  --content-dimmed: light-dark(var(--color-zinc-400), var(--color-zinc-500));
  --content-on-primary: light-dark(var(--color-white), var(--color-zinc-800));

  /* === Backgrounds === */
  --background-base: light-dark(var(--color-white), var(--color-zinc-800));
  --background-subtle: light-dark(
    color-mix(in srgb, var(--background-base), black 2%),
    color-mix(in srgb, var(--background-base), white 2%)
  );
  --background-emphasis: light-dark(
    color-mix(in srgb, var(--background-base), black 4%),
    color-mix(in srgb, var(--background-base), white 4%)
  );

  /* === Surfaces === */
  --surface: light-dark(var(--color-white), var(--color-zinc-800));
  --surface-overlay: light-dark(var(--color-white), var(--color-zinc-800));

  /* === Inputs === */
  --background-input: light-dark(var(--color-white), var(--color-zinc-900));
  --background-input-disabled: color-mix(in srgb, var(--background-input), black 4%);

  /* === Borders === */
  --border-base: light-dark(var(--color-zinc-300), var(--color-zinc-700));
  --border-subtle: color-mix(in srgb, var(--border-base), transparent 50%);
  --border-input: var(--border-base);

  /* === Focus States === */
  --border-focus: light-dark(var(--color-blue-400), var(--color-blue-500));
  --ring-focus: light-dark(--alpha(var(--color-blue-500) / 20%), --alpha(var(--color-blue-500) / 30%));
  --ring-focus-danger: light-dark(var(--color-red-100), --alpha(var(--color-red-600) / 30%));

  /* === Layout === */
  --radius-base: var(--radius-lg);
  --shadow-base: 0 1px 2px 0 rgb(0 0 0 / 0.05);
}

@theme inline {
  /* A bunch of TailwindCSS4 definitions here based on the variables above*/
}
```

Everything's customizable - primary colors, text, backgrounds, borders, radius, shadows. All through CSS variables.

Here's a quick example I'm testing with:

```
[data-theme="tangerine"] {
  color-scheme: light;

  --primary: #ff9300;
  --content: #8b7355;
  --border-base: #f0e0d0;
  --content-on-primary: #ffebd8;
  --background-base: #fffdfb;
  --background-emphasis: var(--background-base);
  --surface-overlay: #fff9f0;
  --shadow-base: 1px 1px 0px 0px rgba(255, 147, 0, 0.4);
}
```

And here's what it looks like:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/e9d2796f-2fa3-4dce-9daa-a37e1d2ccc82" />

The idea is you only override what you need. Want a different brand color? Just change `--primary`. Want something totally different? Override everything.

---

Heads up - there'll be some breaking changes. Mostly just making things more consistent. Like changing button's `variant="solid"` to `variant="primary"` so it matches the `--primary` color variable.

Also tweaking some default colors slightly (like `border-zinc-200` to `border-zinc-300`). Nothing major, just making things more consistent across the board.

---

Still figuring out a few things:

- **Variable names**: Some of the hardest parts 😄 Should it be `content` or `foreground`? `primary` or `brand`? 
- **How specific to get**: Like, do we really need `--background-input` and `--border-input` just for inputs? Or should we just use `--border-base` everywhere? Same applies for a bunch of other things.
- **Keeping Tailwind defaults intact**: I'm trying not to mess with Tailwind's built-in utilities. So instead of changing what `rounded-md` means, I created `rounded-base`. Makes more sense - if you set `--radius-md` to something huge, it's not really "medium" anymore, right?

Keep in mind I'm still tweaking these names and values. Just wanted to give you an idea of where this is heading.

---

What do you think? Would this work for your projects? Any ideas or suggestions?
