### DISCUSSION TITLE
Integrating with Fly.io deployment

### DISCUSSION THREAD

**Discussion by tjl2** [fluxonui/fluxon#21] [General]
Hi 👋 

I've been enjoying using Fluxon in a project recently. I have just finished jumping through a few hoops to get the Hex repo added during a Fly deployment build process, so wanted to share in case it's useful to anybody else.

I deploy my app through a GitHub Action (as outlined [here](https://fly.io/docs/launch/continuous-deployment-with-github-actions/#main-content-start)) and occasionally locally with `flyctl`. For both methods, you need to make it possible for the build process to have access to your Fluxon license key and the Hex repo's public key so that you can enable Docker to run `mix hex.repo add fluxon …` during the build.

You don't want to commit your license/auth key into your repo in plain text, so below are the steps needed to avoid that and get everything working.

### Modifying your Dockerfile

The Dockerfile that is used during releases of your Phoenix app will have a command where the dependencies are installed:

```
RUN mix deps.get --only $MIX_ENV
```

When this tries to run, you will of course get failures by default when `mix` tries to find Fluxon. To get around this, you need a command to run first to add the Fluxon Hex repo, and this is where you need access to your sensitive keys.

Add the following `RUN` command prior to the `RUN mix deps.get` one:

```
RUN --mount=type=secret,id=FLUXON_PUB_KEY \
    --mount=type=secret,id=FLUXON_AUTH_KEY \
    export FLUXON_PUB_KEY=$(cat /run/secrets/FLUXON_PUB_KEY) && \
    export FLUXON_AUTH_KEY=$(cat /run/secrets/FLUXON_AUTH_KEY) && \
    mix hex.repo add fluxon https://repo.fluxonui.com \
    --fetch-public-key $FLUXON_PUB_KEY --auth-key $FLUXON_AUTH_KEY
```

### Providing the keys to the Docker build process

If you're running `fly deploy` locally, you want to store your license/auth key and in local env variables called `FLUXON_AUTH_KEY` and `FLUXON_PUB_KEY`, e.g.:

```
export FLUXON_PUB_KEY="blah"
export FLUXON_AUTH_KEY="license-key"
```

Then you need to run `fly deploy` with two `--build-secrets` arguments, so that they will be stored as secrets that can be passed along to Docker, via those `mount`s, like so:

```
fly deploy --build-secret FLUXON_AUTH_KEY=$FLUXON_AUTH_KEY \
--build-secret FLUXON_PUB_KEY=$FLUXON_PUB_KEY
```

- - -

If you're using the GitHub Action to deploy your app, then you need to store your Fluxon keys as Actions repository secrets in your repo's settings (`https://github.com/:user/:repo/settings/secrets/actions`), so that the Action jobs can access them.

Store these as `FLUXON_AUTH_KEY` and `FLUXON_PUB_KEY`, with the correct values.

Next, modify your Action's YAML in your `.github/workflows` directory to access these secrets and pass them as `--build-secret` arguments. My workflow is only small and hadn't been altered from the default, so I'll paste it in full here:

```yaml
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only \
          --build-secret FLUXON_PUB_KEY="${{ secrets.FLUXON_PUB_KEY }}" \
          --build-secret FLUXON_AUTH_KEY="${{ secrets.FLUXON_AUTH_KEY }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

I hope this is helpful!
